Simple Counter without auth
postech-dao/near pull request #20
Opened 2022-07-11 07:59 UTC by kyungmin-postech

## Type of this PR
> Select at least one type
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix
- [ ] Dependency, Environment, Build related update 
- [ ] Documentation
- [ ] Other tiny fix 

## Describe your changes
Using UnordereMap to generate simple counter without auth 
Used designated account name(kmlee) for test 

### Reference     
https://github.com/near-examples/rust-status-message/blob/master/src/lib.rs
https://github.com/near-examples/rust-counter/blob/01-use-hashmap/contract/src/lib.rs
https://www.near-sdk.io/testing/unit-tests

## Issue ticket number and other helpful resource

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] Leave reference about this pull request, if exist (ex. discord message, google docs, etc)
- [X] If it is a core feature, I have added thorough tests.

## Checklist after creating a pull request
- [X] Mention reviews in discord channel directly

2022-07-12 12:54 UTC, happyhappy-jun requested changes
커밋 메세지와 무관한 내용이 커밋에 담겨있습니다. interactive rebase 와 force push 를 이용해서 한 번 고쳐봅니다. 

p.s. cli 로 이걸 하려면 굉장히 어렵습니다. `fork` 와 같은 버전관리 툴을 한번 사용해봅시다. 만약 도움이 필요하다면, 핑을 찍거나 저녁에 제가 디코에 있는 거 같을때 보이스챗으로 도와드리겠습니다

2022-07-12 12:54 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +    user_counters: UnorderedMap<String, i16>,
기존의 요구사항보다 난이도 높은 것을 구현하셨군요. 그래도 혹시 시간이 된다면, 요구사항에 맞춰서 `UnorderedMap` 을 빼고 구현을 조금 수정해봅시다. 

또한, 요구사항에서 정의된 counter 의 자료형 (`u64`) 를 지켜서 한 번 수정해봅시다

2022-07-12 12:54 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +        let caller = "kmlee".to_string();
caller 가 어떠한 임의의 계정으로 고정이 되어있습니다

2022-07-12 12:54 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +            None => 0i16
get을 했는데, 어떠한 값도 찾을 수 없다면, 0을 리턴하는 게 좋을까요? 아니면, panic 으로 터트리는게 더 좋을까요?

만약에 존재하지 않는 계정을 increase 하려고 하면 뭐가 문제일지 함수 명과 함께 생각해봅니다

2022-07-12 12:54 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +            None => 0i16
위 코멘트와 비슷한 맥락이지만, 이쪽은 더 위험합니다. 다행히 지금은 자료형이 `i16` signed 이지만, `u64`에서는 무슨 일이 벌어질까요?

2022-07-12 12:54 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +    pub fn delete(&mut self, k: String) {
use fommatter

2022-07-21 08:07 UTC, kyungmin-postech commented on simple-counter/src/lib.rs
> +        let caller = "kmlee".to_string();
env의 signer account로 변경했습니다!

2022-07-21 08:07 UTC, kyungmin-postech commented on simple-counter/src/lib.rs
> +            None => 0i16
None의 경우 panic으로 수정했습니다

2022-07-21 08:08 UTC, kyungmin-postech commented on simple-counter/src/lib.rs
> +            None => 0i16
자료형을 수정하고 이 또한 panic으로 수정했습니다

2022-07-31 04:12 UTC, closed without merging