Implmenet simple counter with auth
postech-dao/near pull request #22
Opened 2022-07-13 01:25 UTC by junsoo37

## Type of this PR
> Select at least one type
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix
- [ ] Dependency, Environment, Build related update 
- [ ] Documentation
- [ ] Other tiny fix 

## Describe your changes
- auth를 포함한 simple counter 구현입니다.

## Issue ticket number and other helpful resource

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Leave reference about this pull request, if exist (ex. discord message, google docs, etc)
- [ ] If it is a core feature, I have added thorough tests.

## Checklist after creating a pull request
- [ ] Mention reviews in discord channel directly

2022-07-13 01:28 UTC, junsoo37 commented
`UnorderedSet`으로 구현하고자 했으나, near_bindgen의 serialize trait 조건과 충돌이 존재하여 Vec으로 변경했습니다.
serialize trait을 UnorderedSet에 구현하려다 시간이 소모되어 Vec으로 작성했어요.

2022-07-13 01:30 UTC, junsoo37 commented
리뷰 편의상 main 브랜치로 타겟 브랜치 설정하겠습니다. upstream 레포 제 브랜치에 main 변경사항이 반영되어있지 않아서요.

2022-07-13 17:38 UTC, happyhappy-jun requested changes
새로운 인증 계정을 추가하거나, 삭제하는 기능이 있어야 할 것 같습니다. 최초 배포시에 인자로 넣어준 계정이 영원 불변한 권한을 가지고 있으면 위험할 것 같네요. 

최초 배포자 (컨트랙트 오너) 만이 새로운 인증 계정을 Create Delete 할 수 있는 기능을 추가해 주실 수 있나요?

2022-07-13 17:38 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +    }
```suggestion
    pub fn new(val: u64, auth: Vec<AccountId>) -> Self {
        let mut this = Self{
            count: val,
            auth_ids: UnorderedSet::new(StorageKey::AuthAccount),
        };

        for auth_id in auth {
            this.auth_ids.insert(&auth_id);
        }

        this
    }
```
이 처럼 구현하면, `UnorderedSet` 의 요구사항을 만족하면서 구현 할 수 있을 것 같습니다. `StorageKey::AuthAccount` 는 위쪽에 따로 정의해주면 될 것 같습니다. 

```rust
#[derive(BorshStorageKey, BorshSerialize)]
pub enum StorageKey {
    AuthAccount,
}
```

[Reference](https://github.com/near-examples/nft-series/blob/e674b75391580b6e5707da59ab0116d3a81c4077/market/src/lib.rs)

2022-07-13 17:38 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +    }
한 함수가 두개의 역할을 하고 있습니다. 

만약에 increase 에서 숫자가 안 올라가서 오류 메세지와 트레이스를 봐야할때, 굳이 이를 합치는게 6개월 뒤에 내가 디버깅 할때 좋을지, 아닐지 생각해볼 만한 문제인 것 같습니다

2022-07-13 17:38 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +        value <= max_transaction_value
1. (요청) 고정된 값을 굳이 함수에서 부를 필요가 없을 것 같습니다. 객체의 멤버 변수등으로 박아두고 쓰는게 더 좋아 보입니다
2. (질문) 해당 요구사항은 어디서 나온 요구사항인가요?

2022-07-13 17:38 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +        if self.validate_transaction(trans) {
만약에 validate 에 실패했을때 에러메세지가 없습니다. 이 상태에서 만약에 validate 에 실패하는 트랜잭션이 오게 되면, 유저는 트랜잭션이 정상 처리되는 것을 보지만 실제론 아무런 상태 변화가 일어나지 않죠. panic 을 일으키는 등의 사용자가 알 수 있는 에러 발생이 필요할 것 같습니다

2022-07-13 17:38 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +        let mut contract = State {
`new` 를 이용한 생성자를 impl 했으면 생성자를 사용해서 객체를 만들어줍시다

2022-07-13 17:38 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +            value: 5,
테스트에 모든 인자들이 매직 넘버로 박혀있습니다. 이렇게 되면 왜 이런 값이 들어가는지 무슨 값인지 알기 힘들기 때문에, 고쳐주면 가독성 높은 테스트를 만들 수 있을 것입니다. 

[Helpful docs](https://prodo-developer.tistory.com/118)

2022-07-14 13:23 UTC, junsoo37 reviewed
무언가 요구사항이 꼬인듯하여 아래 내용은 요구사항 재확인 후 함께 반영하도록 하겠습니다.

> 최초 배포자 (컨트랙트 오너) 만이 새로운 인증 계정을 Create Delete 할 수 있는 기능을 추가해 주실 수 있나요?

2022-07-14 13:23 UTC, junsoo37 commented on simple-counter/src/lib.rs
> +        value <= max_transaction_value
다음 [simple-counter 요구사항](https://github.com/postech-dao/contract/blob/main/docs/simple-counter.md)을 참고해서 작성했어요. 무언가 이곳을 비롯하여 요구사항이 꼬인것 같군요

2022-07-14 13:23 UTC, junsoo37 commented on simple-counter/src/lib.rs
> +    }
transaction validation 조건 추가, 삭제에 대한 유연성 및 validation 로직의 가독성을 위해 합치는 편을 선호합니다.
에러 트레이스 관점에서도 validation_transaction에서 에러 -> validation 로직에 포함된 특정 메소드(조건)에서 에러 를 통해 파악하기 수월할 것이라 생각되는데, 블록체인 분야에서 보통 사용되지 않는 패턴인가요?

2022-07-14 13:23 UTC, junsoo37 commented on simple-counter/src/lib.rs
> +        if self.validate_transaction(trans) {
특정 Transaction이 반영되지 않고 전체 시스템은 굴러가야한다는 의도로 panic을 안 넣었는데 별개이겠군요. panic 추가하겠습니다.

2022-07-14 13:31 UTC, junsoo37 commented on simple-counter/src/lib.rs
> +        value <= max_transaction_value
위 문서 내용 외의 요구사항이 존재할까요?

2022-07-15 00:10 UTC, junsoo37 commented on simple-counter/src/lib.rs
> +    }
자주 사용하게 될 패턴으로 보이네요. 좋은 refer 공유 감사합니다 반영했습니다.

2022-07-15 00:12 UTC, junsoo37 commented on simple-counter/src/lib.rs
> +        value <= max_transaction_value
1. 개념적으로 State의 멤버 변수로 넣을 정도인가 라는 생각이 들어요. State에 대해 쭉 고정된 값으로 작용할 것이고 해당 validation 메소드 외에는 사용되지 않을 것으로 보여서요. 어떻게 생각하시나요?

2022-07-15 00:12 UTC, junsoo37 commented on simple-counter/src/lib.rs
> +        if self.validate_transaction(trans) {
반영했습니다.

2022-07-15 00:12 UTC, junsoo37 commented on simple-counter/src/lib.rs
> +        let mut contract = State {
놓쳤네요 반영했습니다.

2022-07-15 00:17 UTC, junsoo37 commented on simple-counter/src/lib.rs
> +            value: 5,
매직넘버를 지양하는 것 동의합니다. 
다만 테스트 코드이고 현 로직상 테스트 코드 사이에 공유될 일이 거의 없는 값들이라서 변수를 정의하기 애매한 부분이 있네요. rust [docs test 파트](https://doc.rust-lang.org/book/ch11-01-writing-tests.html)에서도 이러한 간단한 로직에 대한 테스트 코드에서 변수를 정의하지 않아서 참고하기 힘드네요.
우선 가독성 늘리고자 state value 시작값은 10으로 통일했습니다.

2022-07-17 00:33 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +        value <= max_transaction_value
아 제가 요구사항 파악을 제대로 못한 것 같네요.

2022-07-17 01:47 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +            value: 5,
`현 로직상 테스트 코드 사이에 공유될 일이 거의 없는 값들이라서 변수를 정의하기 애매한 부분이 있네요` 그렇네요. 공유되는 경우도 없고, 값 끼리의 연산이 있어야하는 것도 아니니 넣어놔도 괜찮을 것 같습니다

2022-07-17 21:12 UTC, junha1 commented
@happyhappy-jun [이 코멘트]( https://github.com/postech-dao/near/pull/22#pullrequestreview-1037721369)가 나온 배경이 잘 이해가 가지 않습니다. 컨트랙트의 요구사항이 아니고, `simpler-counter`의 목적 (교육 및 CI/CD 및 빌드사이클 테스트용)상 필요하지도 않은 것 같습니다. 설령 정말로 필요하다고 해도 이 PR에서 마무리 해야 할 이유가 있는 feature도 아니고요.

2022-07-17 21:19 UTC, junha1 submitted a review, later dismissed
현재 전반적으로 니어 컨트랙트의 에러핸들링 방식에 대해 조사가 부족한 것 같습니다. 유닛테스트에서는 컨트랙트 VM을 사용하는 것이기 아니기 때문에 통합테스트를 만들면서 좀 자세히 알아봅시다.

2022-07-18 01:02 UTC, happyhappy-jun commented
> @happyhappy-jun [이 코멘트](https://github.com/postech-dao/near/pull/22#pullrequestreview-1037721369)가 나온 배경이 잘 이해가 가지 않습니다. 컨트랙트의 요구사항이 아니고, `simpler-counter`의 목적 (교육 및 CI/CD 및 빌드사이클 테스트용)상 필요하지도 않은 것 같습니다. 설령 정말로 필요하다고 해도 이 PR에서 마무리 해야 할 이유가 있는 feature도 아니고요.

네네 이건 말씀해주신데로 이 PR 에서 필요한 기능도 아닐꺼 같아서 추후에 필요할때 하면 될 것 같습니다

2022-07-18 04:28 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +    }
재사용되는 로직이니 합치는 거 자체는 문제 없을 것 같습니다. 

그거랑 별개로 수정되었으면 하는 부분이 있는데, 

1. `authenticate, check, validate` 이렇게 세개의 동사가 혼용되고 있고, 통일이 조금 필요해 보입니다. 
2. `authenticate, check`로 시작하는데, 에러 메세지는 `validation`으로 시작하고 있습니다. 1번과 별개로 함수명과 에러 코드는 맞춰야할 것 같습니다. 
3. 마지막으로 세 함수 모두 bool 을 리턴하는 함수인데, 절대로 false 를 리턴하는 케이스가 없습니다. false 가 뜰 경우는 모두 panic 하죠. 이러면 굳이 bool 리턴형을 유지하기 보다 void 가 맞는데, 체크 로직 함수가 void 인건 좀 이상할 꺼 같네요. 그러면 bool 을 유용하게 쓸 수 있는 형태가 읽기 좋을 것 같습니다
4. bool 을 리턴하는 함수라면 네이밍을 is~~로 컨벤션을 잡는게 좋을 것 같습니다. like [this ](https://docs.serde.rs/indexmap/map/struct.Iter.html#method.is_sorted)

궁극적으로 아래와 같은 코드의 형태가 되었으면 좋겠다는 희망입니다
```java
    public SearchRequest(String[] args) {
         if (args.length != 4) {
             throw new IllegalArgumentException(
                 "There should be exactly 4 arguments provided");
         }

         this.passengerNum = validatePassengerNum(args[0]);
         this.departDate = validateDate(args[1]);
         this.toDestination = isInvalidString(args[3]);
         this.fromDestination = isInvalidString(args[2]);

         if (fromDestination.equalsIgnoreCase(toDestination)) {
             throw new IllegalArgumentException("From and To Destinations cannot be the same. " + 
                                                 "You input " + fromDestination);
         }
     }

     private LocalDate validateDate(String stringDate) {
        bool check = isInvalidString(stringDate);

        // Defend logic at the top
        if (!check) {
            throw new IllegalArgumentException("You have provided the following argument, " + 
                         " but it cannot be null or empty: " + s);
        }
        return parseData(stringDate)
     }
    // bool function must return meaningful true and false
     private bool isInvalidString(String s) {
         return (s == null || s.trim().isEmpty())
     }
```

2022-07-18 04:28 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +    #[should_panic]
should_panic 에 expected panic 메세지를 추가 할 수 있습니다. 추가 가능할까요?

```rust
    #[test]
    #[should_panic(expected = "Divide result is zero")]
    fn test_specific_panic() {
        divide_non_zero_result(1, 10);
    }
```

2022-07-18 04:28 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +    }
추가로, `check_transaction_value` 은 멤버 메소드가 아닌 associated function 으로 짜신거 같은데, 의도 하신건가요?

2022-07-18 22:45 UTC, junsoo37 commented on simple-counter/src/lib.rs
> +    }
함수 네이밍 및 리턴 타입 반영했습니다. 좋네요 :)
check_transaction_value의 경우 State 멤버 변수와 인터랙션 할 부분이 없기에 associated function으로 작성했습니다.

2022-07-18 22:46 UTC, junsoo37 commented on simple-counter/src/lib.rs
> +    #[should_panic]
추가했습니다~!

2022-07-19 16:23 UTC, happyhappy-jun commented on simple-counter/src/lib.rs
> +    }
네 좋습니다. 

사실 맘만 같아서는, `is_valid_transaction_value` 는 `Struct Transaction` 을 `impl` 해서 그 쪽에 넣어버리고 싶긴한데... 나중에 Transaction 쪽도 impl 하게 된다면 그때 생각해보면 될 거 같습니다

2022-07-20 03:31 UTC, happyhappy-jun approved these changes

2022-07-20 03:33 UTC, happyhappy-jun commented
close #11

2022-07-20 03:34 UTC, happyhappy-jun commented
resolve #11

2022-07-20 05:36 UTC, junsoo37 commented on simple-counter/src/lib.rs
> +    }
네 확인했습니다. 구체적인 리뷰 감사해요

2022-07-20 05:37 UTC, merged