setup js-interact server
postech-dao/near pull request #55
Opened 2022-08-14 07:24 UTC by imnotkind

## Type of this PR
> Select at least one type
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix
- [x] Dependency, Environment, Build related update 
- [ ] Documentation
- [ ] Other tiny fix 

## Describe your changes
js-interact dummy api 서버 코드 작성했습니다.
원래 zero-install 과 typescript관련 에러가 좀 있어서 해결하는데 힘들었었는데 어찌어찌 만지다 보니 해결된 것 같습니다.

## Issue ticket number and other helpful resource
#52 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Leave reference about this pull request, if exist (ex. discord message, google docs, etc)
- [ ] If it is a core feature, I have added thorough tests.

## Checklist after creating a pull request
- [x] Mention reviews in discord channel directly

2022-08-21 13:52 UTC, happyhappy-jun requested changes
- eslint, prettier 추가 해주실수 있을까요?
- 폴더 이름하고 모듈이름을 고민해봤는데 ts-interact 로 적는게 좋을꺼 같습니다. 
- dist 는 빌드 아웃 폴더인데, 커밋에서 삭제해주세요

2022-08-21 13:52 UTC, happyhappy-jun commented on js-interact/index.test.ts
> +      expect(response.headers['content-type']).toMatch('/json');
중복된 라인이 있습니다. 삭제해주세요

2022-08-21 13:52 UTC, happyhappy-jun commented on js-interact/index.test.ts
> +      expect(response.body).toEqual({ a: 123, b: 'teststring', c:[1,2,3] });
한 테스트에서 너무 많은 expect가 있는 거 같아요. 한 개의 테스트에 한 개의 expect 가 있어야한다고 주장하는 의견도 있지만, 그정도까지는 아니지만, 200이 오는 것, 리턴이 json 으로 오는 것, 페이로드와 동일한 리스폰스가 오는 것은 세개의 별개의 테스트인거 같습니다! 중복 코드가 문제라면, Context: 성공적인 리스폰스가 왔을때, It: 각 케이스  이렇게 해서 beforeEach 로 리퀘를 보내는 것도 방법일 것 같습니다

2022-08-21 13:52 UTC, happyhappy-jun commented on js-interact/index.test.ts
> +jsInteract.close();
new line at EOF

2022-08-21 13:52 UTC, happyhappy-jun commented on js-interact/JsInteract.ts
> +            console.log(arg);
삭제해야할꺼 같습니다

2022-08-21 13:52 UTC, happyhappy-jun commented on js-interact/JsInteract.ts
> +    private echo(a : number, b: string, c: number[]) {
비즈니스 로직이랑 라우터가 같은 파일안에 있어서 이번 PR 에는 아니지만, 추후에 분리하는게 좋을꺼 같습니다

2022-08-31 14:58 UTC, imnotkind commented
혹시 제대로 빌드가 안 되는 상황에 도움이 될까봐 빌드아웃 폴더도 포함하는게 좋을까 했는데, 역시 포함 안 하는게 나으려나요?

2022-08-31 18:59 UTC, imnotkind commented on js-interact/index.test.ts
> +      expect(response.body).toEqual({ a: 123, b: 'teststring', c:[1,2,3] });
dummy 자체를 없애서 일단 저 부분의 코드 자체를 없앴습니다! 원래 그냥 샘플로 넣어둔 거라서 추후 형식을 정하면 좋을 것 같습니다

2022-09-03 13:54 UTC, happyhappy-jun approved these changes
큰 문제는 없을 꺼 같아 추후에 빌드 파일을 제거 하는 방향으로 가는게 좋을꺼 같습니다. 빌드가 안되면 빌드 문제를 해결하도록 하죠. 일단 다른 작업을 위해 머지하고 다른 PR 에서 해결하도록 하죠

2022-09-03 13:54 UTC, merged